name: Job Summaries

on: 
  pull_request:
  workflow_dispatch:

jobs:
  Summary:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: Echo me!
        id: tml
        run: echo "hello :rocket:" >> $GITHUB_STEP_SUMMARY

      - name: Create sticky comment
        uses: marocchino/sticky-pull-request-comment@v2.2.0
        with:
          recreate: true
          message: |
            # :rocket: ${{ github.actor }} Pull request Succesfully Deployed! :rocket:
            
            Thank you for raising your pull request.
            
            | Step ID :computer: |  Result :clipboard: |
            |---           |                       ---|
            |  **Test 1**  | `${{steps.tml.outcome}}` |
            |  **Test 2**  | `${{steps.tml.outcome}}` |

            *This Action was created by @PardusEidolon*
