name: Job Summaries

on: 
  pull_request:
  workflow_dispatch:

jobs:
  Summary:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        
      - id: chkout
        run: |
          ctime=$(date)
          echo "::set-output name=actionchk::$ctime"
      - name: Echo me!
        id: tml
        run: echo "hello :rocket:" >> $GITHUB_STEP_SUMMARY

      - name: Create sticky comment
        uses: marocchino/sticky-pull-request-comment@v2.2.0
        with:
          recreate: true
          message: |
            # :rocket: **${{ github.actor }}** Pull request Succesfully Deployed! :rocket:
            
            Thank you for raising your pull request.
            
            | Step ID :clipboard: | Result :microscope: |   attempts :computer: |
            |---|---|---|
            |  **Test 1**  | ${{steps.tml.outcome}} | ${{ github.run_attempt }} | 
            |  **Test 2**  | ${{steps.tml.outcome}} | ${{ github.run_attempt }} | 
            |  **Test 3**  | ${{steps.tml.outcome}} | ${{ github.run_attempt }} | 
            |  **Test 4**  | ${{steps.tml.outcome}} | ${{ github.run_attempt }} |

            ${{steps.chkout.outputs.actionchk}}

            *This Action was created by @PardusEidolon*
